/* Creative Hub Page */
function CreativePage({ isLoading = false }) {
  const [selectedHook, setSelectedHook] = useState('all');
  if (isLoading) return <SkeletonGenericPage title="Creative Hub" />;
  const hooks = ['all', 'pain_point', 'social_proof', 'scarcity', 'identity', 'curiosity'];
  const hookLabels = { all: 'All', pain_point: 'Pain Point', social_proof: 'Social Proof', scarcity: 'Scarcity', identity: 'Identity', curiosity: 'Curiosity' };

  const filtered = CREATIVE_DRAFTS.filter(c => selectedHook === 'all' || c.hook === selectedHook);

  return (
    <div>
      <div className="page-header">
        <div>
          <div className="page-title">Creative Hub</div>
          <div className="page-subtitle">Khaliji Arabic ad copy drafts · Generated by Claude</div>
        </div>
        <button className="btn btn-primary btn-sm">+ Generate Variants</button>
      </div>

      {/* Hook filter */}
      <div className="tab-bar fade-in">
        {hooks.map(h => (
          <button key={h} className={`tab-btn ${selectedHook === h ? 'active' : ''}`}
            onClick={() => setSelectedHook(h)}>{hookLabels[h]}</button>
        ))}
      </div>

      {/* Creative cards */}
      <div className="grid-2 fade-in fade-in-1" style={{ marginBottom: 0 }}>
        {filtered.map(draft => (
          <CreativeCard key={draft.id} draft={draft} />
        ))}
      </div>

      {/* Guidelines */}
      <div className="card mt-16 fade-in fade-in-2" style={{ marginTop: 20 }}>
        <div className="card-header">
          <span className="card-title">Creative Guidelines</span>
        </div>
        <div className="grid-2" style={{ marginBottom: 0 }}>
          <div>
            <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 8 }}>Copy Rules</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
              {[
                'Hook in first 5 words',
                'Primary text: 50–90 characters',
                'Headline: ≤ 25 characters',
                'Rotate hook types weekly',
                '5 variants per ad set per week min',
              ].map((r, i) => (
                <div key={i} className="flex items-center gap-8" style={{ gap: 8, fontSize: 12, color: 'var(--text-secondary)' }}>
                  <span style={{ color: 'var(--accent)', fontSize: 10 }}>▸</span> {r}
                </div>
              ))}
            </div>
          </div>
          <div>
            <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 8 }}>Approved CTAs</div>
            <div className="flex" style={{ flexWrap: 'wrap', gap: 6 }}>
              {['احصل عليه', 'اطلب الآن', 'اكتشف المزيد', 'جرب الآن', 'اعرف أكثر'].map((cta, i) => (
                <span key={i} style={{
                  background: 'var(--accent-bg)', color: 'var(--accent)',
                  padding: '4px 10px', borderRadius: 4, fontSize: 13,
                  fontFamily: "'Plus Jakarta Sans', 'Noto Sans Arabic', system-ui",
                  direction: 'rtl',
                }}>{cta}</span>
              ))}
            </div>
            <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 8, marginTop: 16 }}>Avoid</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
              {['Unverified product claims', 'Religious content', 'Gendered assumptions outside audience', 'Prices unless confirmed'].map((r, i) => (
                <div key={i} style={{ fontSize: 12, color: 'var(--danger)' }}>✗ {r}</div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

/* ── Creative Card ────────────────────────────────────── */
function CreativeCard({ draft }) {
  const [showTranslation, setShowTranslation] = useState(false);
  const hookColors = {
    pain_point: 'var(--danger)', social_proof: 'var(--info)',
    scarcity: 'var(--warning)', identity: 'var(--accent)', curiosity: 'var(--tiktok)',
  };
  const hookLabel = {
    pain_point: 'Pain Point', social_proof: 'Social Proof',
    scarcity: 'Scarcity', identity: 'Identity', curiosity: 'Curiosity',
  };

  return (
    <div className="card" style={{ borderTop: `3px solid ${hookColors[draft.hook]}` }}>
      <div className="flex items-center justify-between" style={{ marginBottom: 12 }}>
        <div className="flex items-center gap-8" style={{ gap: 8 }}>
          <PlatformTag platform={draft.platform} />
          <span style={{
            fontSize: 10, fontWeight: 700, fontFamily: 'var(--font-mono)',
            color: hookColors[draft.hook], textTransform: 'uppercase',
            padding: '2px 6px', background: `${hookColors[draft.hook]}18`, borderRadius: 3,
          }}>{hookLabel[draft.hook]}</span>
        </div>
        <StatusBadge status={draft.status} />
      </div>

      {/* Arabic content */}
      <div className="ar" style={{
        background: 'var(--bg-surface)', borderRadius: 'var(--radius-sm)',
        padding: '14px 16px', marginBottom: 10,
      }}>
        <div style={{ fontSize: 18, fontWeight: 700, marginBottom: 8, lineHeight: 1.4 }}>
          {draft.headline}
        </div>
        <div style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.7, marginBottom: 10 }}>
          {draft.primaryText}
        </div>
        <div style={{
          display: 'inline-block', background: 'var(--accent)',
          color: 'var(--text-inverse)', padding: '6px 16px',
          borderRadius: 'var(--radius-sm)', fontWeight: 700, fontSize: 13,
        }}>
          {draft.cta}
        </div>
      </div>

      {/* Translation toggle */}
      <button onClick={() => setShowTranslation(!showTranslation)}
        style={{
          background: 'none', border: 'none', color: 'var(--text-tertiary)',
          cursor: 'pointer', fontSize: 11, fontFamily: 'var(--font-body)',
          padding: '2px 0',
        }}>
        {showTranslation ? '▾ Hide translation' : '▸ Show English translation'}
      </button>

      {showTranslation && (
        <div style={{
          fontSize: 12, color: 'var(--text-tertiary)', marginTop: 6,
          padding: '8px 12px', background: 'var(--bg-surface)', borderRadius: 'var(--radius-sm)',
          fontStyle: 'italic',
        }}>
          <strong>{draft.headlineEn}</strong>
          <br />{draft.primaryTextEn}
        </div>
      )}

      {/* Meta */}
      <div className="flex items-center justify-between mt-8" style={{ marginTop: 10 }}>
        <span className="text-xs text-tertiary truncate" style={{ maxWidth: '60%' }}>{draft.campaign}</span>
        <div className="flex gap-8" style={{ gap: 6 }}>
          {draft.status === 'draft' && (
            <button className="btn btn-success btn-sm" style={{ padding: '3px 8px', fontSize: 11 }}>Approve</button>
          )}
          <button className="btn btn-ghost btn-sm" style={{ padding: '3px 8px', fontSize: 11 }}>Edit</button>
        </div>
      </div>
    </div>
  );
}

Object.assign(window, { CreativePage, CreativeCard });
